### ISSUE TITLE
Add old data from epifor pipeline or elsewhere

### ISSUE THREAD

**Issue by sualehasif** [epidemics/epimodel#1]

**Comment by gavento** [comment]
Extract the following from [regions.yaml](https://github.com/epidemics/epifor/blob/master/data/regions.yaml)
* All the data for the region columns (see [column defs](https://github.com/epidemics/epimodel/blob/86545e166544ed5d32e925ffea1dbd854ced6cf2/epimodel/regions.py#L80))
  * Lat/Lon are low priority
* Include Gleam mini-=regions in the rows (`kind="city"`)
* Extract hospital beds (preferably to separate Code-indexed CSV)
* Ignore special regions (EU, Middle east), forget yaml "keys".

**Comment by gavento** [comment]
Closed by work from Annie and https://github.com/epidemics/epimodel-covid-data/pull/5
