### ISSUE TITLE
Evaluate and potentially integrate gleam model with asymptomatic transmission route

### ISSUE THREAD

**Issue by lagerros** [epidemics/epimodel#16]
This needs:
* A brief sanity check
* To be integrated into production

File available here: https://epidemicforecasting.slack.com/archives/CV3KMT19V/p1586078368049800

**Comment by gavento** [comment]
Closing since:
* There was no consensus in the thread linked above
* The switch is used-side (just provide this XML as input to batch generation)
* Note that the model has more compartments than Gleam allows to export, so we would not see all of them.
