### ISSUE TITLE
Update csse.py to have merged US-states in csse.csv

### ISSUE THREAD

**Issue by sualehasif** [epidemics/epimodel#17]
Since csse separated the US and global, we should merge the global and US_states into one table so that regions and the US are somewhat in sync.

**Comment by gavento** [comment]
The task is to complete https://github.com/epidemics/epimodel/blob/master/epimodel/imports/johns_hopkins.py to also include US per-state data from https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series
It already imports the global data. 

US data:
* Does not have Recovered (so naturally use NaNs for it and Active)
* Has a much finer division - for now sum it up by states (they are already in our region DB and are searchable; see e.g. how the import handles other country provinces).

**Comment by gavento** [comment]
Fixed by Euan, thanks!
