### ISSUE TITLE
Make web_export fail more gracefully so I can iterate faster

### ISSUE THREAD

**Issue by AcesoUnderGlass** [epidemics/epimodel#53]
Right now if web_export partially succeeds and then fails, it's a pain to restart. You need to delete the modified hdf5 file and bring back the original (hope you saved a copy). Otherwise you get an error like `Exception: Would overwrite existing `new_fraction` in <Batch out/batch-2020-05-08T00_19_12.041254+00_00.hdf5>!` It would be much easier if you could fiddle with what you needed to and then hit `web_export` (or `workflow-gleam-to-web`), and it just worked.

One possible solution to this is to output to a different hdf5 file than is used as input, which I think is already on the table, and either mark bad runs as safe to delete or let the user configure a flag to delete them

**Comment by hnykda** [comment]
Do you mind if I recreate the issue in the covid repo and close this one (and I may disable issues entirely for this repo)? As it's not possible to use cross-repo board: https://github.com/epidemics/covid/projects/1

**Comment by AcesoUnderGlass** [comment]
@hnykda sure. Is that where everything should go? I just started an am still learning conventions.

**Comment by mathijshenquet** [comment]
Yes for project management reasons. All issues should be assigned the project `covid` and prioritized on the board here: https://github.com/epidemics/covid/projects/1.

**Comment by hnykda** [comment]
> @hnykda sure. Is that where everything should go? I just started an am still learning conventions.

Yeah, sorry for the confusion, I will try to write it ASAP, you couldn't know...

**Comment by hnykda** [comment]
https://github.com/epidemics/covid/issues/448
